language: scala

sudo: required

env:
  - JDK=oraclejdk8
  - JDK=openjdk8

scala:
  - 2.12.0
  - 2.12.1
  - 2.12.2
  - 2.12.3
  - 2.12.4
  - 2.12.5
  - 2.12.6
  - 2.12.7

os: linux

dist: trusty

before_script:
  - jdk_switcher use $JDK

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=1G -J-Xms1G test